### ISSUE TITLE
module 'gast' has no attribute 'Node'

### ISSUE THREAD

**Issue by LUOyk1999** [google-deepmind/digraph_transformer#1]
Thanks for sharing your code.

I have got your code running. I followed the steps:
python3 -m venv /tmp/digraph_transformer
source /tmp/digraph_transformer/bin/activate
pip3 install --upgrade pip setuptools wheel
pip3 install -r requirements.txt

But now I got an error in the dataflow_parser.py at line 229:
Traceback (most recent call last):
  File "dataflow_parser.py", line 221, in <module>
    class OGB_ASTWalker(ast.NodeVisitor):  # pylint: disable=invalid-name
  File "dataflow_parser.py", line 229, in OGB_ASTWalker
    def generic_visit(self, node: ast.Node):
AttributeError: module 'gast' has no attribute 'Node'

I would really appreciate your help here, thanks!

**Comment by sigeisler** [comment]
Sorry, I have not seen your issue earlier. As this is only an (erroneous) typing annotation, you may delete `: ast.Node`. I will also shortly create a pull request that should make it easier to reproduce the results.
